// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: Fri Nov 26 09:27:01 UTC 2021

package main

import (
	"flag"

	// This Service
	"github.com/mises-id/mises-websitesvc/handlers"
	"github.com/mises-id/mises-websitesvc/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	cfg := server.DefaultConfig
	cfg = handlers.SetConfig(cfg)

	server.Run(cfg)
}
