// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: websitesvc.proto

// The package name determines the name of the directories that truss creates
// for `package echo;` truss will create the directory "echo-service".

package websitesvc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/metaverse/truss/deftree/googlethirdparty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PageQuick struct {
	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	NextId string `protobuf:"bytes,2,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
	Total  uint64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *PageQuick) Reset()         { *m = PageQuick{} }
func (m *PageQuick) String() string { return proto.CompactTextString(m) }
func (*PageQuick) ProtoMessage()    {}
func (*PageQuick) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{0}
}
func (m *PageQuick) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PageQuick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PageQuick.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PageQuick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuick.Merge(m, src)
}
func (m *PageQuick) XXX_Size() int {
	return m.Size()
}
func (m *PageQuick) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuick.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuick proto.InternalMessageInfo

func (m *PageQuick) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PageQuick) GetNextId() string {
	if m != nil {
		return m.NextId
	}
	return ""
}

func (m *PageQuick) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Page struct {
	TotalRecords uint64 `protobuf:"varint,1,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	PageSize     uint64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNum      uint64 `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	TotalPage    uint64 `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{1}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Page.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return m.Size()
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetTotalRecords() uint64 {
	if m != nil {
		return m.TotalRecords
	}
	return 0
}

func (m *Page) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Page) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Page) GetTotalPage() uint64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

type WebsiteCategoryListRequest struct {
	ListNum uint64 `protobuf:"varint,1,opt,name=list_num,json=listNum,proto3" json:"list_num,omitempty"`
}

func (m *WebsiteCategoryListRequest) Reset()         { *m = WebsiteCategoryListRequest{} }
func (m *WebsiteCategoryListRequest) String() string { return proto.CompactTextString(m) }
func (*WebsiteCategoryListRequest) ProtoMessage()    {}
func (*WebsiteCategoryListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{2}
}
func (m *WebsiteCategoryListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsiteCategoryListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsiteCategoryListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsiteCategoryListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteCategoryListRequest.Merge(m, src)
}
func (m *WebsiteCategoryListRequest) XXX_Size() int {
	return m.Size()
}
func (m *WebsiteCategoryListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteCategoryListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteCategoryListRequest proto.InternalMessageInfo

func (m *WebsiteCategoryListRequest) GetListNum() uint64 {
	if m != nil {
		return m.ListNum
	}
	return 0
}

type WebsiteCategory struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc       string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	TypeString string `protobuf:"bytes,4,opt,name=type_string,json=typeString,proto3" json:"type_string,omitempty"`
}

func (m *WebsiteCategory) Reset()         { *m = WebsiteCategory{} }
func (m *WebsiteCategory) String() string { return proto.CompactTextString(m) }
func (*WebsiteCategory) ProtoMessage()    {}
func (*WebsiteCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{3}
}
func (m *WebsiteCategory) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsiteCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsiteCategory.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsiteCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteCategory.Merge(m, src)
}
func (m *WebsiteCategory) XXX_Size() int {
	return m.Size()
}
func (m *WebsiteCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteCategory.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteCategory proto.InternalMessageInfo

func (m *WebsiteCategory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WebsiteCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WebsiteCategory) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *WebsiteCategory) GetTypeString() string {
	if m != nil {
		return m.TypeString
	}
	return ""
}

type WebsiteCategoryListResponse struct {
	Code uint64             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data []*WebsiteCategory `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (m *WebsiteCategoryListResponse) Reset()         { *m = WebsiteCategoryListResponse{} }
func (m *WebsiteCategoryListResponse) String() string { return proto.CompactTextString(m) }
func (*WebsiteCategoryListResponse) ProtoMessage()    {}
func (*WebsiteCategoryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{4}
}
func (m *WebsiteCategoryListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsiteCategoryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsiteCategoryListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsiteCategoryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteCategoryListResponse.Merge(m, src)
}
func (m *WebsiteCategoryListResponse) XXX_Size() int {
	return m.Size()
}
func (m *WebsiteCategoryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteCategoryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteCategoryListResponse proto.InternalMessageInfo

func (m *WebsiteCategoryListResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WebsiteCategoryListResponse) GetData() []*WebsiteCategory {
	if m != nil {
		return m.Data
	}
	return nil
}

type WebsitePageRequest struct {
	Type              string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	WebsiteCategoryId string `protobuf:"bytes,2,opt,name=website_category_id,json=websiteCategoryId,proto3" json:"website_category_id,omitempty"`
	Keywords          string `protobuf:"bytes,3,opt,name=Keywords,proto3" json:"Keywords,omitempty"`
	Paginator         *Page  `protobuf:"bytes,4,opt,name=paginator,proto3" json:"paginator,omitempty"`
}

func (m *WebsitePageRequest) Reset()         { *m = WebsitePageRequest{} }
func (m *WebsitePageRequest) String() string { return proto.CompactTextString(m) }
func (*WebsitePageRequest) ProtoMessage()    {}
func (*WebsitePageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{5}
}
func (m *WebsitePageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsitePageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsitePageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsitePageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsitePageRequest.Merge(m, src)
}
func (m *WebsitePageRequest) XXX_Size() int {
	return m.Size()
}
func (m *WebsitePageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsitePageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebsitePageRequest proto.InternalMessageInfo

func (m *WebsitePageRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *WebsitePageRequest) GetWebsiteCategoryId() string {
	if m != nil {
		return m.WebsiteCategoryId
	}
	return ""
}

func (m *WebsitePageRequest) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *WebsitePageRequest) GetPaginator() *Page {
	if m != nil {
		return m.Paginator
	}
	return nil
}

type WebsitePageResponse struct {
	Code      uint64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data      []*Website `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Paginator *Page      `protobuf:"bytes,3,opt,name=paginator,proto3" json:"paginator,omitempty"`
}

func (m *WebsitePageResponse) Reset()         { *m = WebsitePageResponse{} }
func (m *WebsitePageResponse) String() string { return proto.CompactTextString(m) }
func (*WebsitePageResponse) ProtoMessage()    {}
func (*WebsitePageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{6}
}
func (m *WebsitePageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsitePageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsitePageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsitePageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsitePageResponse.Merge(m, src)
}
func (m *WebsitePageResponse) XXX_Size() int {
	return m.Size()
}
func (m *WebsitePageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsitePageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebsitePageResponse proto.InternalMessageInfo

func (m *WebsitePageResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WebsitePageResponse) GetData() []*Website {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WebsitePageResponse) GetPaginator() *Page {
	if m != nil {
		return m.Paginator
	}
	return nil
}

type Website struct {
	Id                string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WebsiteCategoryId string           `protobuf:"bytes,2,opt,name=website_category_id,json=websiteCategoryId,proto3" json:"website_category_id,omitempty"`
	Title             string           `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url               string           `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Logo              string           `protobuf:"bytes,5,opt,name=logo,proto3" json:"logo,omitempty"`
	Desc              string           `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Type              string           `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	WebsiteCategory   *WebsiteCategory `protobuf:"bytes,8,opt,name=website_category,json=websiteCategory,proto3" json:"website_category,omitempty"`
}

func (m *Website) Reset()         { *m = Website{} }
func (m *Website) String() string { return proto.CompactTextString(m) }
func (*Website) ProtoMessage()    {}
func (*Website) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{7}
}
func (m *Website) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Website) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Website.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Website) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Website.Merge(m, src)
}
func (m *Website) XXX_Size() int {
	return m.Size()
}
func (m *Website) XXX_DiscardUnknown() {
	xxx_messageInfo_Website.DiscardUnknown(m)
}

var xxx_messageInfo_Website proto.InternalMessageInfo

func (m *Website) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Website) GetWebsiteCategoryId() string {
	if m != nil {
		return m.WebsiteCategoryId
	}
	return ""
}

func (m *Website) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Website) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Website) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Website) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Website) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Website) GetWebsiteCategory() *WebsiteCategory {
	if m != nil {
		return m.WebsiteCategory
	}
	return nil
}

type WebsiteRecommendRequest struct {
	ListNum uint64 `protobuf:"varint,1,opt,name=list_num,json=listNum,proto3" json:"list_num,omitempty"`
}

func (m *WebsiteRecommendRequest) Reset()         { *m = WebsiteRecommendRequest{} }
func (m *WebsiteRecommendRequest) String() string { return proto.CompactTextString(m) }
func (*WebsiteRecommendRequest) ProtoMessage()    {}
func (*WebsiteRecommendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{8}
}
func (m *WebsiteRecommendRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsiteRecommendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsiteRecommendRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsiteRecommendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteRecommendRequest.Merge(m, src)
}
func (m *WebsiteRecommendRequest) XXX_Size() int {
	return m.Size()
}
func (m *WebsiteRecommendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteRecommendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteRecommendRequest proto.InternalMessageInfo

func (m *WebsiteRecommendRequest) GetListNum() uint64 {
	if m != nil {
		return m.ListNum
	}
	return 0
}

type WebsiteRecommendResponse struct {
	Code uint64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data []*Website `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (m *WebsiteRecommendResponse) Reset()         { *m = WebsiteRecommendResponse{} }
func (m *WebsiteRecommendResponse) String() string { return proto.CompactTextString(m) }
func (*WebsiteRecommendResponse) ProtoMessage()    {}
func (*WebsiteRecommendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{9}
}
func (m *WebsiteRecommendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsiteRecommendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsiteRecommendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsiteRecommendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteRecommendResponse.Merge(m, src)
}
func (m *WebsiteRecommendResponse) XXX_Size() int {
	return m.Size()
}
func (m *WebsiteRecommendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteRecommendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteRecommendResponse proto.InternalMessageInfo

func (m *WebsiteRecommendResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WebsiteRecommendResponse) GetData() []*Website {
	if m != nil {
		return m.Data
	}
	return nil
}

type WebsiteImportRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (m *WebsiteImportRequest) Reset()         { *m = WebsiteImportRequest{} }
func (m *WebsiteImportRequest) String() string { return proto.CompactTextString(m) }
func (*WebsiteImportRequest) ProtoMessage()    {}
func (*WebsiteImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{10}
}
func (m *WebsiteImportRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsiteImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsiteImportRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsiteImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteImportRequest.Merge(m, src)
}
func (m *WebsiteImportRequest) XXX_Size() int {
	return m.Size()
}
func (m *WebsiteImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteImportRequest proto.InternalMessageInfo

func (m *WebsiteImportRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type WebsiteImportResponse struct {
	Code uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *WebsiteImportResponse) Reset()         { *m = WebsiteImportResponse{} }
func (m *WebsiteImportResponse) String() string { return proto.CompactTextString(m) }
func (*WebsiteImportResponse) ProtoMessage()    {}
func (*WebsiteImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6b9bd7fb837846, []int{11}
}
func (m *WebsiteImportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebsiteImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebsiteImportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebsiteImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteImportResponse.Merge(m, src)
}
func (m *WebsiteImportResponse) XXX_Size() int {
	return m.Size()
}
func (m *WebsiteImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteImportResponse proto.InternalMessageInfo

func (m *WebsiteImportResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*PageQuick)(nil), "websitesvc.PageQuick")
	proto.RegisterType((*Page)(nil), "websitesvc.Page")
	proto.RegisterType((*WebsiteCategoryListRequest)(nil), "websitesvc.WebsiteCategoryListRequest")
	proto.RegisterType((*WebsiteCategory)(nil), "websitesvc.WebsiteCategory")
	proto.RegisterType((*WebsiteCategoryListResponse)(nil), "websitesvc.WebsiteCategoryListResponse")
	proto.RegisterType((*WebsitePageRequest)(nil), "websitesvc.WebsitePageRequest")
	proto.RegisterType((*WebsitePageResponse)(nil), "websitesvc.WebsitePageResponse")
	proto.RegisterType((*Website)(nil), "websitesvc.Website")
	proto.RegisterType((*WebsiteRecommendRequest)(nil), "websitesvc.WebsiteRecommendRequest")
	proto.RegisterType((*WebsiteRecommendResponse)(nil), "websitesvc.WebsiteRecommendResponse")
	proto.RegisterType((*WebsiteImportRequest)(nil), "websitesvc.WebsiteImportRequest")
	proto.RegisterType((*WebsiteImportResponse)(nil), "websitesvc.WebsiteImportResponse")
}

func init() { proto.RegisterFile("websitesvc.proto", fileDescriptor_7f6b9bd7fb837846) }

var fileDescriptor_7f6b9bd7fb837846 = []byte{
	// 805 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xae, 0x13, 0x6f, 0x13, 0xbf, 0xd0, 0x6d, 0x78, 0xd9, 0xa5, 0xde, 0x44, 0x64, 0xb3, 0x5e,
	0xa0, 0x95, 0x2a, 0xc5, 0xa2, 0x45, 0x42, 0x5c, 0x41, 0x20, 0x55, 0xa0, 0x55, 0xf1, 0x1e, 0x2a,
	0xe5, 0x12, 0x39, 0xf6, 0xac, 0x33, 0x60, 0x7b, 0x82, 0x3d, 0xde, 0x90, 0xbd, 0xb1, 0xbf, 0x60,
	0x25, 0x7e, 0x01, 0x12, 0x3f, 0x84, 0x23, 0xc7, 0x4a, 0x5c, 0x38, 0xa2, 0x96, 0xbf, 0xc0, 0x1d,
	0xcd, 0x78, 0xe2, 0x38, 0x6e, 0x9a, 0x82, 0xb4, 0xb7, 0xf7, 0xbe, 0x79, 0xf9, 0xde, 0x37, 0xef,
	0x7b, 0xe3, 0x40, 0x7b, 0x4e, 0x26, 0x29, 0xe5, 0x24, 0x7d, 0xe9, 0x0d, 0x67, 0x09, 0xe3, 0x0c,
	0x61, 0x85, 0x74, 0xbf, 0x0c, 0x28, 0x9f, 0x66, 0x93, 0xa1, 0xc7, 0x22, 0x3b, 0x22, 0xdc, 0x7d,
	0x49, 0x92, 0x94, 0xd8, 0x3c, 0xc9, 0xd2, 0xd4, 0xf6, 0xc9, 0x0b, 0x9e, 0x10, 0x62, 0x07, 0x8c,
	0x05, 0x21, 0xe1, 0x53, 0x9a, 0xf8, 0x33, 0x37, 0xe1, 0x0b, 0xdb, 0x8d, 0x63, 0xc6, 0x5d, 0x4e,
	0x59, 0x9c, 0xe6, 0x94, 0xd6, 0x39, 0x18, 0xe7, 0x6e, 0x40, 0xbe, 0xcd, 0xa8, 0xf7, 0x3d, 0x3e,
	0x80, 0x7b, 0x21, 0x8d, 0x28, 0x37, 0xb5, 0x81, 0x76, 0xa4, 0x3b, 0x79, 0x82, 0x07, 0xd0, 0x88,
	0xc9, 0x8f, 0x7c, 0x4c, 0x7d, 0xb3, 0x36, 0xd0, 0x8e, 0x0c, 0x67, 0x57, 0xa4, 0x67, 0xbe, 0x28,
	0xe7, 0x8c, 0xbb, 0xa1, 0x59, 0xcf, 0xcb, 0x65, 0x62, 0xbd, 0xd6, 0x40, 0x17, 0x94, 0xf8, 0x14,
	0xf6, 0x24, 0x32, 0x4e, 0x88, 0xc7, 0x12, 0x3f, 0x55, 0xac, 0xef, 0x48, 0xd0, 0xc9, 0x31, 0xec,
	0x81, 0x31, 0x73, 0x03, 0x32, 0x4e, 0xe9, 0x2b, 0x22, 0xe9, 0x75, 0xa7, 0x29, 0x80, 0xe7, 0xf4,
	0x15, 0xc1, 0x47, 0x20, 0xe3, 0x71, 0x9c, 0x45, 0xaa, 0x47, 0x43, 0xe4, 0xcf, 0xb2, 0x08, 0xdf,
	0x07, 0xc8, 0xc9, 0x05, 0x60, 0xea, 0xf2, 0xd0, 0x90, 0x88, 0xe8, 0x6d, 0x7d, 0x0a, 0xdd, 0x8b,
	0x7c, 0x56, 0x5f, 0xb8, 0x9c, 0x04, 0x2c, 0x59, 0x7c, 0x43, 0x53, 0xee, 0x90, 0x1f, 0x32, 0x92,
	0x72, 0xc1, 0x1b, 0xd2, 0x94, 0x4b, 0xde, 0x5c, 0x54, 0x43, 0xe4, 0xcf, 0xb2, 0xc8, 0xfa, 0x0e,
	0xf6, 0x2b, 0x3f, 0xc4, 0xfb, 0x50, 0xa3, 0xbe, 0xac, 0x33, 0x9c, 0x1a, 0xf5, 0x11, 0x41, 0x8f,
	0xdd, 0x88, 0xa8, 0x61, 0xc8, 0x58, 0x60, 0x3e, 0x49, 0x3d, 0xa9, 0xd2, 0x70, 0x64, 0x8c, 0x8f,
	0xa1, 0xc5, 0x17, 0x33, 0x32, 0x4e, 0x79, 0x42, 0xe3, 0x40, 0x6a, 0x34, 0x1c, 0x10, 0xd0, 0x73,
	0x89, 0x58, 0x13, 0xe8, 0x6d, 0x14, 0x99, 0xce, 0x58, 0x9c, 0x4a, 0x4e, 0x8f, 0xf9, 0x44, 0x29,
	0x94, 0x31, 0xda, 0xa0, 0xfb, 0x2e, 0x77, 0xcd, 0xda, 0xa0, 0x7e, 0xd4, 0x3a, 0xe9, 0x0d, 0x4b,
	0x2b, 0x52, 0xa1, 0x72, 0x64, 0xa1, 0xf5, 0xab, 0x06, 0xa8, 0x4e, 0xc4, 0x60, 0x96, 0x13, 0x40,
	0xd0, 0x85, 0x10, 0x75, 0x2b, 0x19, 0xe3, 0x10, 0x3a, 0x8a, 0x6e, 0xec, 0x29, 0x92, 0x95, 0xe7,
	0xef, 0xce, 0xd7, 0xe9, 0xcf, 0x7c, 0xec, 0x42, 0xf3, 0x6b, 0xb2, 0x98, 0x4b, 0x6b, 0xf3, 0x7b,
	0x17, 0x39, 0x0e, 0xa5, 0xad, 0x34, 0x76, 0x39, 0x4b, 0xe4, 0xcd, 0x5b, 0x27, 0xed, 0xb2, 0x58,
	0xa9, 0x65, 0x55, 0x22, 0x96, 0xa6, 0xb3, 0x26, 0x73, 0xcb, 0x0c, 0x0e, 0xd7, 0x66, 0xd0, 0xd9,
	0x30, 0x83, 0xfc, 0xee, 0xeb, 0x22, 0xea, 0x77, 0x8b, 0xf8, 0x47, 0x83, 0x86, 0x62, 0xb8, 0x61,
	0xfa, 0xff, 0x1d, 0x8e, 0x78, 0x1b, 0x94, 0x87, 0x44, 0x4d, 0x26, 0x4f, 0xb0, 0x0d, 0xf5, 0x2c,
	0x09, 0xd5, 0x2a, 0x88, 0x50, 0x5c, 0x30, 0x64, 0x01, 0x33, 0xef, 0xe5, 0x46, 0x88, 0xb8, 0x58,
	0xa6, 0xdd, 0xd2, 0x32, 0x2d, 0x0d, 0x6b, 0x94, 0x0c, 0xfb, 0xaa, 0xf8, 0x44, 0x14, 0x9a, 0xcc,
	0xa6, 0xbc, 0xe6, 0xd6, 0xc5, 0xd8, 0xaf, 0xa8, 0xb5, 0x3e, 0x81, 0x83, 0xe5, 0xe0, 0x88, 0xc7,
	0xa2, 0x88, 0xc4, 0xfe, 0x7f, 0x78, 0x29, 0x17, 0x60, 0xde, 0xfc, 0xd5, 0x5b, 0xb0, 0xcd, 0x3a,
	0x85, 0x07, 0x0a, 0x38, 0x8b, 0x66, 0x2c, 0x29, 0x5e, 0x6d, 0x0f, 0x8c, 0x17, 0x34, 0x24, 0xe3,
	0x99, 0xcb, 0xa7, 0xca, 0x99, 0xa6, 0x00, 0xce, 0x5d, 0x3e, 0xb5, 0x8e, 0xe1, 0x61, 0xe5, 0x47,
	0xb7, 0x4b, 0x39, 0xf9, 0x4d, 0x07, 0xb8, 0x28, 0xda, 0xe3, 0x2f, 0xab, 0xe5, 0x2b, 0x3f, 0x44,
	0xfc, 0x68, 0xcb, 0x14, 0x4b, 0x9f, 0x93, 0xee, 0xe1, 0x9d, 0x75, 0xb9, 0x16, 0xeb, 0xb3, 0xd7,
	0x7f, 0xfc, 0xfd, 0x73, 0xed, 0x14, 0xdf, 0xb3, 0xab, 0xbe, 0xd9, 0x62, 0xaa, 0xa3, 0x47, 0x78,
	0xb0, 0xf9, 0xc4, 0xc6, 0x39, 0xb4, 0x4a, 0xef, 0x03, 0xfb, 0x1b, 0x5a, 0x96, 0xde, 0x77, 0xf7,
	0xf1, 0xad, 0xe7, 0x4a, 0xca, 0xa1, 0x94, 0xf2, 0x04, 0xf7, 0x96, 0x0d, 0x6d, 0xf1, 0x21, 0x1d,
	0xb5, 0xf1, 0xfe, 0x1a, 0x60, 0xe3, 0x1b, 0x0d, 0xda, 0x55, 0x9f, 0xf1, 0xe9, 0x26, 0xf7, 0x2a,
	0xbb, 0xd3, 0xfd, 0x60, 0x7b, 0x91, 0x12, 0xf2, 0xb1, 0x14, 0x72, 0x8c, 0x58, 0xf4, 0x4d, 0x96,
	0x35, 0xa3, 0x87, 0xd8, 0xb9, 0x89, 0xda, 0xf8, 0x93, 0x06, 0x7b, 0x6b, 0x66, 0xe3, 0x60, 0x43,
	0xab, 0xb5, 0xe5, 0xe9, 0x3e, 0xd9, 0x52, 0xa1, 0x94, 0x1c, 0x4b, 0x25, 0x1f, 0xe2, 0x7e, 0xd1,
	0x93, 0xca, 0x82, 0x11, 0x62, 0xbb, 0x02, 0xd9, 0x9f, 0x9b, 0xbf, 0x5f, 0xf5, 0xb5, 0xcb, 0xab,
	0xbe, 0xf6, 0xd7, 0x55, 0x5f, 0x7b, 0x73, 0xdd, 0xdf, 0xb9, 0xbc, 0xee, 0xef, 0xfc, 0x79, 0xdd,
	0xdf, 0x99, 0xec, 0xca, 0x3f, 0xd6, 0xd3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x35, 0x63, 0x37,
	0x3e, 0xbf, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebsitesvcClient is the client API for Websitesvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebsitesvcClient interface {
	WebsiteCategoryList(ctx context.Context, in *WebsiteCategoryListRequest, opts ...grpc.CallOption) (*WebsiteCategoryListResponse, error)
	WebsitePage(ctx context.Context, in *WebsitePageRequest, opts ...grpc.CallOption) (*WebsitePageResponse, error)
	WebsiteRecommend(ctx context.Context, in *WebsiteRecommendRequest, opts ...grpc.CallOption) (*WebsiteRecommendResponse, error)
	WebsiteImport(ctx context.Context, in *WebsiteImportRequest, opts ...grpc.CallOption) (*WebsiteImportResponse, error)
}

type websitesvcClient struct {
	cc *grpc.ClientConn
}

func NewWebsitesvcClient(cc *grpc.ClientConn) WebsitesvcClient {
	return &websitesvcClient{cc}
}

func (c *websitesvcClient) WebsiteCategoryList(ctx context.Context, in *WebsiteCategoryListRequest, opts ...grpc.CallOption) (*WebsiteCategoryListResponse, error) {
	out := new(WebsiteCategoryListResponse)
	err := c.cc.Invoke(ctx, "/websitesvc.Websitesvc/WebsiteCategoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websitesvcClient) WebsitePage(ctx context.Context, in *WebsitePageRequest, opts ...grpc.CallOption) (*WebsitePageResponse, error) {
	out := new(WebsitePageResponse)
	err := c.cc.Invoke(ctx, "/websitesvc.Websitesvc/WebsitePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websitesvcClient) WebsiteRecommend(ctx context.Context, in *WebsiteRecommendRequest, opts ...grpc.CallOption) (*WebsiteRecommendResponse, error) {
	out := new(WebsiteRecommendResponse)
	err := c.cc.Invoke(ctx, "/websitesvc.Websitesvc/WebsiteRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websitesvcClient) WebsiteImport(ctx context.Context, in *WebsiteImportRequest, opts ...grpc.CallOption) (*WebsiteImportResponse, error) {
	out := new(WebsiteImportResponse)
	err := c.cc.Invoke(ctx, "/websitesvc.Websitesvc/WebsiteImport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsitesvcServer is the server API for Websitesvc service.
type WebsitesvcServer interface {
	WebsiteCategoryList(context.Context, *WebsiteCategoryListRequest) (*WebsiteCategoryListResponse, error)
	WebsitePage(context.Context, *WebsitePageRequest) (*WebsitePageResponse, error)
	WebsiteRecommend(context.Context, *WebsiteRecommendRequest) (*WebsiteRecommendResponse, error)
	WebsiteImport(context.Context, *WebsiteImportRequest) (*WebsiteImportResponse, error)
}

// UnimplementedWebsitesvcServer can be embedded to have forward compatible implementations.
type UnimplementedWebsitesvcServer struct {
}

func (*UnimplementedWebsitesvcServer) WebsiteCategoryList(ctx context.Context, req *WebsiteCategoryListRequest) (*WebsiteCategoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebsiteCategoryList not implemented")
}
func (*UnimplementedWebsitesvcServer) WebsitePage(ctx context.Context, req *WebsitePageRequest) (*WebsitePageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebsitePage not implemented")
}
func (*UnimplementedWebsitesvcServer) WebsiteRecommend(ctx context.Context, req *WebsiteRecommendRequest) (*WebsiteRecommendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebsiteRecommend not implemented")
}
func (*UnimplementedWebsitesvcServer) WebsiteImport(ctx context.Context, req *WebsiteImportRequest) (*WebsiteImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebsiteImport not implemented")
}

func RegisterWebsitesvcServer(s *grpc.Server, srv WebsitesvcServer) {
	s.RegisterService(&_Websitesvc_serviceDesc, srv)
}

func _Websitesvc_WebsiteCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebsiteCategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsitesvcServer).WebsiteCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/websitesvc.Websitesvc/WebsiteCategoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsitesvcServer).WebsiteCategoryList(ctx, req.(*WebsiteCategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websitesvc_WebsitePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebsitePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsitesvcServer).WebsitePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/websitesvc.Websitesvc/WebsitePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsitesvcServer).WebsitePage(ctx, req.(*WebsitePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websitesvc_WebsiteRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebsiteRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsitesvcServer).WebsiteRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/websitesvc.Websitesvc/WebsiteRecommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsitesvcServer).WebsiteRecommend(ctx, req.(*WebsiteRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websitesvc_WebsiteImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebsiteImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsitesvcServer).WebsiteImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/websitesvc.Websitesvc/WebsiteImport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsitesvcServer).WebsiteImport(ctx, req.(*WebsiteImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Websitesvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "websitesvc.Websitesvc",
	HandlerType: (*WebsitesvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WebsiteCategoryList",
			Handler:    _Websitesvc_WebsiteCategoryList_Handler,
		},
		{
			MethodName: "WebsitePage",
			Handler:    _Websitesvc_WebsitePage_Handler,
		},
		{
			MethodName: "WebsiteRecommend",
			Handler:    _Websitesvc_WebsiteRecommend_Handler,
		},
		{
			MethodName: "WebsiteImport",
			Handler:    _Websitesvc_WebsiteImport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "websitesvc.proto",
}

func (m *PageQuick) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PageQuick) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Limit))
	}
	if len(m.NextId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.NextId)))
		i += copy(dAtA[i:], m.NextId)
	}
	if m.Total != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Total))
	}
	return i, nil
}

func (m *Page) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Page) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TotalRecords != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.TotalRecords))
	}
	if m.PageSize != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.PageSize))
	}
	if m.PageNum != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.PageNum))
	}
	if m.TotalPage != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.TotalPage))
	}
	return i, nil
}

func (m *WebsiteCategoryListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsiteCategoryListRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ListNum != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.ListNum))
	}
	return i, nil
}

func (m *WebsiteCategory) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsiteCategory) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Desc) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Desc)))
		i += copy(dAtA[i:], m.Desc)
	}
	if len(m.TypeString) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.TypeString)))
		i += copy(dAtA[i:], m.TypeString)
	}
	return i, nil
}

func (m *WebsiteCategoryListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsiteCategoryListResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Code))
	}
	if len(m.Data) > 0 {
		for _, msg := range m.Data {
			dAtA[i] = 0x12
			i++
			i = encodeVarintWebsitesvc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *WebsitePageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsitePageRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.WebsiteCategoryId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.WebsiteCategoryId)))
		i += copy(dAtA[i:], m.WebsiteCategoryId)
	}
	if len(m.Keywords) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Keywords)))
		i += copy(dAtA[i:], m.Keywords)
	}
	if m.Paginator != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Paginator.Size()))
		n1, err1 := m.Paginator.MarshalTo(dAtA[i:])
		if err1 != nil {
			return 0, err1
		}
		i += n1
	}
	return i, nil
}

func (m *WebsitePageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsitePageResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Code))
	}
	if len(m.Data) > 0 {
		for _, msg := range m.Data {
			dAtA[i] = 0x12
			i++
			i = encodeVarintWebsitesvc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Paginator != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Paginator.Size()))
		n2, err2 := m.Paginator.MarshalTo(dAtA[i:])
		if err2 != nil {
			return 0, err2
		}
		i += n2
	}
	return i, nil
}

func (m *Website) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Website) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.WebsiteCategoryId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.WebsiteCategoryId)))
		i += copy(dAtA[i:], m.WebsiteCategoryId)
	}
	if len(m.Title) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Title)))
		i += copy(dAtA[i:], m.Title)
	}
	if len(m.Url) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Url)))
		i += copy(dAtA[i:], m.Url)
	}
	if len(m.Logo) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Logo)))
		i += copy(dAtA[i:], m.Logo)
	}
	if len(m.Desc) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Desc)))
		i += copy(dAtA[i:], m.Desc)
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if m.WebsiteCategory != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.WebsiteCategory.Size()))
		n3, err3 := m.WebsiteCategory.MarshalTo(dAtA[i:])
		if err3 != nil {
			return 0, err3
		}
		i += n3
	}
	return i, nil
}

func (m *WebsiteRecommendRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsiteRecommendRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ListNum != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.ListNum))
	}
	return i, nil
}

func (m *WebsiteRecommendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsiteRecommendResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Code))
	}
	if len(m.Data) > 0 {
		for _, msg := range m.Data {
			dAtA[i] = 0x12
			i++
			i = encodeVarintWebsitesvc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *WebsiteImportRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsiteImportRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.FilePath) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(len(m.FilePath)))
		i += copy(dAtA[i:], m.FilePath)
	}
	return i, nil
}

func (m *WebsiteImportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebsiteImportResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWebsitesvc(dAtA, i, uint64(m.Code))
	}
	return i, nil
}

func encodeVarintWebsitesvc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *PageQuick) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limit != 0 {
		n += 1 + sovWebsitesvc(uint64(m.Limit))
	}
	l = len(m.NextId)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	if m.Total != 0 {
		n += 1 + sovWebsitesvc(uint64(m.Total))
	}
	return n
}

func (m *Page) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalRecords != 0 {
		n += 1 + sovWebsitesvc(uint64(m.TotalRecords))
	}
	if m.PageSize != 0 {
		n += 1 + sovWebsitesvc(uint64(m.PageSize))
	}
	if m.PageNum != 0 {
		n += 1 + sovWebsitesvc(uint64(m.PageNum))
	}
	if m.TotalPage != 0 {
		n += 1 + sovWebsitesvc(uint64(m.TotalPage))
	}
	return n
}

func (m *WebsiteCategoryListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ListNum != 0 {
		n += 1 + sovWebsitesvc(uint64(m.ListNum))
	}
	return n
}

func (m *WebsiteCategory) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Desc)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.TypeString)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	return n
}

func (m *WebsiteCategoryListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovWebsitesvc(uint64(m.Code))
	}
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovWebsitesvc(uint64(l))
		}
	}
	return n
}

func (m *WebsitePageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.WebsiteCategoryId)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Keywords)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	if m.Paginator != nil {
		l = m.Paginator.Size()
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	return n
}

func (m *WebsitePageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovWebsitesvc(uint64(m.Code))
	}
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovWebsitesvc(uint64(l))
		}
	}
	if m.Paginator != nil {
		l = m.Paginator.Size()
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	return n
}

func (m *Website) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.WebsiteCategoryId)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Logo)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Desc)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	if m.WebsiteCategory != nil {
		l = m.WebsiteCategory.Size()
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	return n
}

func (m *WebsiteRecommendRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ListNum != 0 {
		n += 1 + sovWebsitesvc(uint64(m.ListNum))
	}
	return n
}

func (m *WebsiteRecommendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovWebsitesvc(uint64(m.Code))
	}
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovWebsitesvc(uint64(l))
		}
	}
	return n
}

func (m *WebsiteImportRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FilePath)
	if l > 0 {
		n += 1 + l + sovWebsitesvc(uint64(l))
	}
	return n
}

func (m *WebsiteImportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovWebsitesvc(uint64(m.Code))
	}
	return n
}

func sovWebsitesvc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWebsitesvc(x uint64) (n int) {
	return sovWebsitesvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PageQuick) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PageQuick: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PageQuick: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Page) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Page: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Page: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRecords", wireType)
			}
			m.TotalRecords = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalRecords |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageNum", wireType)
			}
			m.PageNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPage", wireType)
			}
			m.TotalPage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalPage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsiteCategoryListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsiteCategoryListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsiteCategoryListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListNum", wireType)
			}
			m.ListNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ListNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsiteCategory) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsiteCategory: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsiteCategory: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Desc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Desc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypeString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsiteCategoryListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsiteCategoryListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsiteCategoryListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &WebsiteCategory{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsitePageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsitePageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsitePageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebsiteCategoryId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebsiteCategoryId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keywords", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keywords = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paginator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Paginator == nil {
				m.Paginator = &Page{}
			}
			if err := m.Paginator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsitePageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsitePageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsitePageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &Website{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paginator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Paginator == nil {
				m.Paginator = &Page{}
			}
			if err := m.Paginator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Website) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Website: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Website: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebsiteCategoryId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebsiteCategoryId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Logo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Logo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Desc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Desc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebsiteCategory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WebsiteCategory == nil {
				m.WebsiteCategory = &WebsiteCategory{}
			}
			if err := m.WebsiteCategory.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsiteRecommendRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsiteRecommendRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsiteRecommendRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListNum", wireType)
			}
			m.ListNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ListNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsiteRecommendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsiteRecommendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsiteRecommendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &Website{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsiteImportRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsiteImportRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsiteImportRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilePath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebsiteImportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebsiteImportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebsiteImportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWebsitesvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebsitesvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWebsitesvc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWebsitesvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWebsitesvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWebsitesvc
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthWebsitesvc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowWebsitesvc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipWebsitesvc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthWebsitesvc
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthWebsitesvc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWebsitesvc   = fmt.Errorf("proto: integer overflow")
)
