// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: Fri Nov 26 09:27:01 UTC 2021

// Package grpc provides a gRPC client for the Websitesvc service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/mises-id/mises-websitesvc/proto"
	"github.com/mises-id/mises-websitesvc/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.WebsitesvcServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var websitecategorylistEndpoint endpoint.Endpoint
	{
		websitecategorylistEndpoint = grpctransport.NewClient(
			conn,
			"websitesvc.Websitesvc",
			"WebsiteCategoryList",
			EncodeGRPCWebsiteCategoryListRequest,
			DecodeGRPCWebsiteCategoryListResponse,
			pb.WebsiteCategoryListResponse{},
			clientOptions...,
		).Endpoint()
	}

	var websitepageEndpoint endpoint.Endpoint
	{
		websitepageEndpoint = grpctransport.NewClient(
			conn,
			"websitesvc.Websitesvc",
			"WebsitePage",
			EncodeGRPCWebsitePageRequest,
			DecodeGRPCWebsitePageResponse,
			pb.WebsitePageResponse{},
			clientOptions...,
		).Endpoint()
	}

	var websiterecommendEndpoint endpoint.Endpoint
	{
		websiterecommendEndpoint = grpctransport.NewClient(
			conn,
			"websitesvc.Websitesvc",
			"WebsiteRecommend",
			EncodeGRPCWebsiteRecommendRequest,
			DecodeGRPCWebsiteRecommendResponse,
			pb.WebsiteRecommendResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		WebsiteCategoryListEndpoint: websitecategorylistEndpoint,
		WebsitePageEndpoint:         websitepageEndpoint,
		WebsiteRecommendEndpoint:    websiterecommendEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCWebsiteCategoryListResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC websitecategorylist reply to a user-domain websitecategorylist response. Primarily useful in a client.
func DecodeGRPCWebsiteCategoryListResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.WebsiteCategoryListResponse)
	return reply, nil
}

// DecodeGRPCWebsitePageResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC websitepage reply to a user-domain websitepage response. Primarily useful in a client.
func DecodeGRPCWebsitePageResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.WebsitePageResponse)
	return reply, nil
}

// DecodeGRPCWebsiteRecommendResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC websiterecommend reply to a user-domain websiterecommend response. Primarily useful in a client.
func DecodeGRPCWebsiteRecommendResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.WebsiteRecommendResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCWebsiteCategoryListRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain websitecategorylist request to a gRPC websitecategorylist request. Primarily useful in a client.
func EncodeGRPCWebsiteCategoryListRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.WebsiteCategoryListRequest)
	return req, nil
}

// EncodeGRPCWebsitePageRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain websitepage request to a gRPC websitepage request. Primarily useful in a client.
func EncodeGRPCWebsitePageRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.WebsitePageRequest)
	return req, nil
}

// EncodeGRPCWebsiteRecommendRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain websiterecommend request to a gRPC websiterecommend request. Primarily useful in a client.
func EncodeGRPCWebsiteRecommendRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.WebsiteRecommendRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
