// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: Fri Nov 26 09:27:01 UTC 2021

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/mises-id/mises-websitesvc/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC WebsitesvcServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.WebsitesvcServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// websitesvc

		websitecategorylist: grpctransport.NewServer(
			endpoints.WebsiteCategoryListEndpoint,
			DecodeGRPCWebsiteCategoryListRequest,
			EncodeGRPCWebsiteCategoryListResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the WebsitesvcServer interface
type grpcServer struct {
	websitecategorylist grpctransport.Handler
}

// Methods for grpcServer to implement WebsitesvcServer interface

func (s *grpcServer) WebsiteCategoryList(ctx context.Context, req *pb.WebsiteCategoryListRequest) (*pb.WebsiteCategoryListResponse, error) {
	_, rep, err := s.websitecategorylist.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.WebsiteCategoryListResponse), nil
}

// Server Decode

// DecodeGRPCWebsiteCategoryListRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC websitecategorylist request to a user-domain websitecategorylist request. Primarily useful in a server.
func DecodeGRPCWebsiteCategoryListRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.WebsiteCategoryListRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCWebsiteCategoryListResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain websitecategorylist response to a gRPC websitecategorylist reply. Primarily useful in a server.
func EncodeGRPCWebsiteCategoryListResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.WebsiteCategoryListResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
